'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');

const { buildSkillSamples, listCandidateFiles, estTokensFor } = require('../src/skill-sampler');
const { extensionsForTechnology } = require('../src/tech-extensions');

/*
 * skill-code-certification, issue 005: deterministic sampler. Same tree ->
 * same sample; exclusions honored; token caps enforced with a declared
 * SamplingMeta (truncated/capReason). No mapping -> not sampleable.
 */

const JS = extensionsForTechnology('React');

let root;
test.beforeEach(() => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), 'ai-sampler-'));
});
test.afterEach(() => {
  fs.rmSync(root, { recursive: true, force: true });
});

function write(rel, content) {
  const abs = path.join(root, rel);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content);
}

test('estTokensFor: ceil(bytes/4)', () => {
  assert.equal(estTokensFor(400), 100);
  assert.equal(estTokensFor(401), 101);
  assert.equal(estTokensFor(0), 0);
});

test('listCandidateFiles: only matching extensions, ordered size DESC then path ASC', () => {
  write('a.js', 'x'.repeat(40));
  write('b.js', 'y'.repeat(400));
  write('sub/c.js', 'z'.repeat(40)); // same size as a.js -> path tiebreak
  write('ignore.py', 'p'.repeat(999));
  const files = listCandidateFiles(root, JS);
  assert.deepEqual(files.map((f) => f.path), ['b.js', 'a.js', 'sub/c.js']);
});

test('listCandidateFiles: excludes build/vendor dirs, lockfiles, *.min.*, *.map, generated', () => {
  write('keep.js', 'k'.repeat(10));
  write('node_modules/dep.js', 'n'.repeat(999));
  write('dist/out.js', 'd'.repeat(999));
  write('.git/hook.js', 'g'.repeat(999));
  write('coverage/cov.js', 'c'.repeat(999));
  write('.next/n.js', 'x'.repeat(999));
  write('out/o.js', 'x'.repeat(999));
  write('vendor/v.js', 'v'.repeat(999));
  write('bundle.min.js', 'm'.repeat(999));
  write('map.js.map', 'm'.repeat(999));
  write('package-lock.json', '{}');
  write('generated.js', '// @generated by tool\nconst x = 1;');
  const files = listCandidateFiles(root, JS);
  assert.deepEqual(files.map((f) => f.path), ['keep.js']);
});

test('buildSkillSamples: reads content, fills SamplingMeta, deterministic across runs', () => {
  write('big.jsx', 'a'.repeat(400));
  write('small.jsx', 'b'.repeat(40));
  const sel = [{ skillId: 1, skillName: 'React', technology: 'React' }];
  const r1 = buildSkillSamples(root, sel);
  const r2 = buildSkillSamples(root, sel);
  assert.deepEqual(r1[0].files.map((f) => f.path), ['big.jsx', 'small.jsx']);
  assert.deepEqual(r1[0].files.map((f) => f.path), r2[0].files.map((f) => f.path));
  const meta = r1[0].meta;
  assert.equal(meta.sampleable, true);
  assert.equal(meta.candidateCount, 2);
  assert.equal(meta.includedCount, 2);
  assert.equal(meta.truncated, false);
  assert.equal(meta.capReason, null);
  assert.equal(meta.estTokens, estTokensFor(400) + estTokensFor(40));
  assert.equal(r1[0].files[0].content, 'a'.repeat(400));
});

test('buildSkillSamples: per-skill cap truncates (capReason per-skill-cap), largest-over-cap skipped', () => {
  write('big.js', 'a'.repeat(400));   // 100 tokens
  write('small.js', 'b'.repeat(40));  // 10 tokens
  const r = buildSkillSamples(root, [{ skillId: 1, skillName: 'React', technology: 'React' }], { perSkillTokenCap: 50 });
  assert.equal(r[0].meta.truncated, true);
  assert.equal(r[0].meta.capReason, 'per-skill-cap');
  assert.deepEqual(r[0].files.map((f) => f.path), ['small.js']);
});

test('buildSkillSamples: run budget truncates (capReason run-budget)', () => {
  write('big.js', 'a'.repeat(400));   // 100 tokens
  write('small.js', 'b'.repeat(40));  // 10 tokens
  const r = buildSkillSamples(root, [{ skillId: 1, skillName: 'React', technology: 'React' }], { runTokenBudget: 50, perSkillTokenCap: 100000 });
  assert.equal(r[0].meta.truncated, true);
  assert.equal(r[0].meta.capReason, 'run-budget');
  assert.deepEqual(r[0].files.map((f) => f.path), ['small.js']);
});

test('buildSkillSamples: run budget is shared ACROSS skills (deterministic by skillId order)', () => {
  write('r.jsx', 'a'.repeat(160)); // React, 40 tokens
  write('s.py', 'b'.repeat(160));  // Django, 40 tokens
  const sel = [
    { skillId: 2, skillName: 'Django', technology: 'Django' },
    { skillId: 1, skillName: 'React', technology: 'React' },
  ];
  // budget only fits one file (40) -> the skillId-ASC-first skill (React=1) gets it
  const r = buildSkillSamples(root, sel, { runTokenBudget: 40 });
  const react = r.find((x) => x.skillId === 1);
  const django = r.find((x) => x.skillId === 2);
  assert.equal(react.meta.includedCount, 1);
  assert.equal(django.meta.includedCount, 0);
  assert.equal(django.meta.truncated, true);
  assert.equal(django.meta.capReason, 'run-budget');
});

test('buildSkillSamples: unmapped technology -> not sampleable, no files', () => {
  write('x.js', 'x'.repeat(40));
  const r = buildSkillSamples(root, [{ skillId: 9, skillName: 'Mainframe', technology: 'COBOL' }]);
  assert.equal(r[0].meta.sampleable, false);
  assert.equal(r[0].files.length, 0);
  assert.equal(r[0].meta.extensions, null);
});
