'use strict';

/*
 * Curated tier roadmap content (talents-ai-score, issue 020 / ADR-013/014).
 *
 * PORTED VERBATIM from
 * active-work/talents-ai-score/build/roadmap-content.md (authored by the
 * product-manager, NOT generated by this CLI or any LLM at runtime —
 * ADR-013's "contenido autorado, no generado en cada run"). This module is
 * the CLI's own copy of that content so it ships with the tool, not left
 * to live only in the meta-repo.
 *
 * One entry per tier JUMP (current tier -> next), keyed by the CURRENT
 * tier's key (T0..T6). The report shows ONLY the entry for
 * `maturity.tierKey` — never the whole ladder at once (source doc: "El
 * informe muestra solo el salto actual → siguiente"). T7 has its own
 * terminal entry (no next jump — "nivel máximo").
 *
 * i18n: prose is AUTHORED IN SPANISH ONLY as of this writing — the source
 * document has no English translation yet (its own frontmatter: "idioma
 * base es-ES; marcado para localización"). Rather than inventing an
 * English translation of authored product content, there is no `en`
 * catalog here; src/render-html.js falls back to this Spanish content with
 * an explicit "pending translation" notice (src/i18n.js's
 * `roadmapPendingTranslation`) instead of silently mistranslating or
 * fabricating prose. Code snippets are LITERAL and never translated in
 * either language (source doc: "Los snippets NO se traducen").
 */

const TIER_JUMPS_ES = {
  T0: {
    title: 'T0 → T1 · Banco vacío → Primera herramienta',
    upgradeWhen: '`totalDetected >= 1` (una herramienta de IA detectada por existencia de fichero/dir/binario/extensión — `detectors.js`).',
    unlocks: 'Tu primera herramienta de IA en el entorno de trabajo. Dejas de alternar con una pestaña de chat aparte: la IA vive donde escribes código y ve el fichero que tienes delante. Es el salto de "consulto a la IA" a "trabajo con la IA".',
    steps: [
      { text: 'Elige una herramienta acorde a cómo trabajas — si vives en la terminal, una CLI agéntica (Claude Code, Codex CLI); si vives en el editor, un asistente de IDE (Copilot, Cursor).', estimate: '5 min' },
      { text: 'Instálala siguiendo la vía oficial de su proveedor.', estimate: '10-15 min' },
      { text: 'Ábrela en un proyecto real y pídele algo que ibas a hacer igualmente (explicar una función, escribir un test).', estimate: '10 min' },
    ],
    snippet: {
      language: 'bash',
      label: 'instalación de una CLI agéntica (deja el binario `claude` en el PATH y `~/.claude`, dos de las señales de T1)',
      filename: null,
      code: '# Claude Code (CLI agéntica) — instalación oficial\nnpm install -g @anthropic-ai/claude-code\n# arráncala una vez en tu proyecto para que cree ~/.claude\nclaude',
    },
    tips: [
      'Empieza por una herramienta, no cinco. El tier premia tenerla, pero tu soltura la da usar una a fondo, no coleccionarlas.',
      'Pruébala en trabajo real desde el minuto uno; los tutoriales de juguete no enseñan dónde te ayuda de verdad.',
    ],
    commonMistakes: [
      'Usar una IA solo en el navegador (chat web) y nada en el entorno local → el CLI no deja rastro de eso y te mantiene en T0. La herramienta mide huella local, no lo que haces en una pestaña.',
      'Instalar la extensión pero en un editor que el CLI no rastrea. Las señales de extensión miran ~/.vscode, ~/.vscode-insiders y ~/.cursor; una extensión en otro editor puede no contar.',
    ],
  },

  T1: {
    title: 'T1 → T2 · Primera herramienta → Banco con notas',
    upgradeWhen: '`context >= 1`, es decir ≥1 fichero de contexto persistente (`instructions + config + rules`: `CLAUDE.md`, `GEMINI.md`, `AGENTS.md`, `.github/copilot-instructions.md`, `.cursorrules`/`.cursor/rules/*.mdc`, `.windsurfrules`/`.windsurf/rules/*.md`, config de Aider/Continue).',
    unlocks: 'Contexto que no tienes que reexplicar cada vez. Un fichero de instrucciones deja escrito cómo es tu proyecto (stack, convenciones, qué no tocar) y la IA lo lee en cada sesión. El salto de "le repito lo mismo cada mañana" a "ya sabe cómo trabajamos aquí".',
    steps: [
      { text: 'Crea el fichero de instrucciones que corresponda a tu herramienta, en la raíz del proyecto.', estimate: '5 min' },
      { text: 'Escribe lo mínimo que repites siempre: qué es el proyecto, stack, 3-4 convenciones, qué está prohibido tocar.', estimate: '15-20 min' },
      { text: 'Prueba una tarea y ajusta el fichero cuando la IA se salte una convención.', estimate: '10 min' },
    ],
    snippet: {
      language: 'markdown',
      label: 'CLAUDE.md en la raíz del proyecto (su mera existencia cuenta como instructions = 1 y te sube a T2)',
      filename: 'CLAUDE.md',
      code: '# <Nombre del proyecto>\n\n## Qué es\nUna frase sobre qué hace este proyecto y para quién.\n\n## Stack\n- Lenguaje / framework principal\n- Base de datos\n- Cómo se ejecutan los tests\n\n## Convenciones\n- Estilo de commits.\n- Cómo se nombran los ficheros.\n- Qué NO tocar sin avisar.',
    },
    tips: [
      'Corto y vivo gana a largo y muerto. Un fichero de 20 líneas que actualizas vale más que uno de 200 que nadie mantiene.',
      'Guárdalo en el repo: viaja con el equipo y no lo pierdes al cambiar de máquina.',
      'Escribe las prohibiciones explícitas ("no toques las migraciones ya aplicadas"): es donde más se desvía la IA sin contexto.',
    ],
    commonMistakes: [
      'Poner las instrucciones en un README o en un fichero con nombre inventado → el CLI solo cuenta los nombres canónicos (CLAUDE.md, .cursorrules, etc.). Nombre equivocado, no sube de tier.',
      'Crear el fichero vacío o solo con el título. Existe, sí, pero no te da lo que el tier promete: el valor está en el contenido, no en el fichero.',
    ],
  },

  T2: {
    title: 'T2 → T3 · Banco con notas → Banco conectado',
    upgradeWhen: '`mcpServers >= 1` (conteo de claves en `mcpServers` de `.mcp.json`, `~/.claude.json`, `.cursor/mcp.json`, `~/.codeium/windsurf/mcp_config.json`, `~/.gemini/settings.json` — `scanner.js::countJsonKeys`).',
    unlocks: 'Conectar tu primer servidor MCP deja de darle a la IA solo tu código: le das acceso a tus datos y sistemas reales (tu base de datos, tu tracker de incidencias, tu documentación) sin copiar y pegar. El salto de "la IA lee mi proyecto" a "la IA consulta mis fuentes" es el que más tiempo ahorra en tareas repetitivas.',
    steps: [
      { text: 'Elige una fuente que consultes a diario (tu BD de desarrollo, tu sistema de tickets, tu sistema de ficheros).', estimate: '5 min' },
      { text: 'Instala un servidor MCP para esa fuente y decláralo en tu config.', estimate: '15-20 min' },
      { text: 'Verifica que la herramienta lo carga (arranca la CLI/editor y comprueba que el servidor aparece disponible).', estimate: '5 min' },
      { text: 'Haz una consulta real que antes hacías a mano (ej. "resume los últimos 5 tickets abiertos").', estimate: '5 min' },
    ],
    snippet: {
      language: 'json',
      label: '.mcp.json en la raíz del proyecto (el CLI cuenta las claves de mcpServers; con una ya subes a T3)',
      filename: '.mcp.json',
      code: '{\n  "mcpServers": {\n    "filesystem": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-filesystem", "./docs"]\n    }\n  }\n}',
    },
    tips: [
      'Empieza por un MCP de solo lectura (filesystem, docs): el valor aparece rápido y el riesgo es mínimo.',
      'Un MCP bien elegido rinde más que cinco a medias. El tier premia tenerlo conectado, pero tu productividad la mueve usarlo.',
      'Guarda el .mcp.json en el repo del proyecto: así viaja con el equipo y no lo pierdes al cambiar de máquina.',
    ],
    commonMistakes: [
      'Configurar el MCP en un fichero que la herramienta no lee (ruta equivocada) → el servidor no arranca y el CLI no lo cuenta. Verifica siempre el paso 3.',
      'Dejar el bloque mcpServers vacío ({}) — cuenta como 0 servidores, no sube de tier.',
      'Pegar credenciales dentro del .mcp.json y subirlo al repo. Usa variables de entorno; nunca claves en claro (además, es justo el tipo de fuga que el AI Footprint evita capturar).',
    ],
  },

  T3: {
    title: 'T3 → T4 · Banco conectado → Herramienta propia',
    upgradeWhen: '`custom >= 1`, es decir ≥1 asset propio reutilizable (`skills + commands + rules`: dirs en `.claude/skills/`, ficheros `.claude/commands/*.md`, o reglas propias de Cursor/Windsurf).',
    unlocks: 'Dejas de escribir el mismo prompt largo una y otra vez: lo conviertes en un asset reutilizable (un comando, una skill) que invocas por su nombre. El salto de "reescribo las instrucciones cada vez" a "tengo mis propias herramientas empaquetadas".',
    steps: [
      { text: 'Identifica un prompt que repites (revisar un PR, generar un test, redactar un changelog).', estimate: '5 min' },
      { text: 'Empaquétalo como comando o skill en la carpeta que tu herramienta reconoce.', estimate: '15-25 min' },
      { text: 'Invócalo por su nombre en una tarea real y púlelo hasta que no tengas que corregirlo.', estimate: '10 min' },
    ],
    snippet: {
      language: 'markdown',
      label: 'una skill propia en .claude/skills/review-diff/SKILL.md (cada subcarpeta de .claude/skills/ cuenta como skills += 1 y te sube a T4)',
      filename: '.claude/skills/review-diff/SKILL.md',
      code: '---\nname: review-diff\ndescription: Revisa el diff actual contra los estándares del proyecto\n---\n1. Muestra el diff frente a la rama base.\n2. Marca cualquier cosa que rompa las convenciones de CLAUDE.md.\n3. Señala tests que falten para el código nuevo.',
    },
    tips: [
      'Empaqueta lo que ya haces cada día, no lo que crees que "deberías" automatizar. El uso real es la señal de qué merece ser un asset.',
      'Nómbralos con verbos claros (review-diff, write-migration): un catálogo legible se usa; uno críptico se olvida.',
    ],
    commonMistakes: [
      'Meter la skill/comando en una carpeta con otro nombre → el CLI cuenta subdirectorios de .claude/skills/ y ficheros .md de .claude/commands/; fuera de ahí no cuenta.',
      'Guardar el comando con extensión distinta de .md en commands/ → no entra en el conteo.',
      'Crear diez comandos de una línea para "subir rápido": cuentan para el número, pero es justo el tipo de inflado que el dato asume como indicativo, no verificado. No te hace mejor; te hace medible.',
    ],
  },

  T4: {
    title: 'T4 → T5 · Herramienta propia → Operador agéntico',
    upgradeWhen: '`hasAgentic` y `mcp >= 1` y `custom >= 1`. `hasAgentic` = tener una CLI agéntica del conjunto AGENTIC_IDS (Claude Code, Aider, Gemini CLI, Codex CLI y Amazon Q, añadido por decisión cerrada #4).',
    unlocks: 'T5 es el punto donde tu setup deja de asistirte paso a paso y empieza a ejecutar tareas de principio a fin: una CLI agéntica que, apoyada en tus MCP y en tus skills/comandos propios, encadena varios pasos sola. Es el salto de "me sugiere" a "lo hace y me lo trae para revisar".',
    steps: [
      { text: 'Asegúrate de tener una CLI agéntica (Claude Code, Aider, Gemini CLI, Codex CLI o Amazon Q). Si trabajas solo en un editor con autocompletado, instala una.', estimate: '15 min' },
      { text: 'Confirma que ya cumples los prerrequisitos de T5: al menos 1 MCP (T3) y al menos 1 skill/comando/regla propia (T4). Si te falta alguno, el CLI te mantiene en T4.', estimate: '5 min' },
      { text: 'Crea un comando propio que orqueste una tarea recurrente completa (ej. "prepara el PR": lint + tests + resumen de cambios).', estimate: '30-45 min' },
      { text: 'Ejecútalo en un flujo real y ajusta hasta que necesites intervenir lo mínimo.', estimate: 'variable' },
    ],
    snippet: {
      language: 'markdown',
      label: 'un comando propio en .claude/commands/prep-pr.md (el CLI cuenta los .md de commands/ como customización)',
      filename: '.claude/commands/prep-pr.md',
      code: '---\ndescription: Prepara una rama para PR — lint, tests y resumen de cambios\n---\n1. Ejecuta el linter y los tests del proyecto; si algo falla, párate y muéstramelo.\n2. Resume en 5 bullets los cambios frente a la rama base.\n3. Redacta un título de PR en Conventional Commits.',
    },
    tips: [
      'El operador agéntico rinde cuando le das límites claros en el comando: qué puede tocar, cuándo parar, qué revisar contigo.',
      'Reutiliza tus MCP dentro del comando (el que conectaste en T3): ahí es donde el agente pasa de "escribe código" a "consulta, decide y actúa".',
      'Un comando que ejecutas cada día vale más que diez que escribiste una vez. Mide por uso, no por cantidad.',
    ],
    commonMistakes: [
      'Tener CLI agéntica y skills, pero ningún MCP → te quedas en T4: T5 exige las tres piezas a la vez.',
      'Crear comandos que solo envuelven un prompt trivial de una línea: cuentan para el número, pero no te dan la orquestación real que el tier promete.',
      'Dar al agente permiso total sin puntos de revisión: sube el tier, pero es la vía más rápida a un cambio que no querías. La ladder mide setup, no criterio — el criterio lo pones tú.',
    ],
  },

  T5: {
    title: 'T5 → T6 · Operador agéntico → Multi-agente',
    upgradeWhen: '`agentCounts.agents >= 2` (≥2 ficheros .claude/agents/*.md con frontmatter name válido — agent-org-chart.js::parseAgentOrgChart).',
    unlocks: 'Dejas de tener un asistente todoterreno y pasas a un equipo de agentes especializados: uno para backend, otro para revisar, otro para tests. Cada uno con su rol y sus herramientas. El salto de "un ayudante que hace de todo" a "un equipo donde cada pieza sabe lo suyo".',
    steps: [
      { text: 'Parte tu trabajo en 2-3 roles claros que hoy mezclas (ej. "escribir código" vs. "revisar").', estimate: '10 min' },
      { text: 'Crea un fichero de agente por rol en .claude/agents/, cada uno con su name, sus tools y su model.', estimate: '20-30 min' },
      { text: 'Úsalos en una tarea real delegando cada parte al agente que toca.', estimate: 'variable' },
    ],
    snippet: {
      language: 'markdown',
      label: 'dos definiciones de agente (dos ficheros con name válido → agents = 2, te sube a T6). El CLI lee solo la estructura del frontmatter (name, tools, model), nunca el cuerpo ni la descripción',
      filename: '.claude/agents/reviewer.md',
      code: '---\nname: reviewer\ntools: Read, Grep\nmodel: sonnet\n---\nRevisa código contra las convenciones del proyecto. No modifica ficheros.',
      secondFile: {
        filename: '.claude/agents/tester.md',
        code: '---\nname: tester\ntools: Read, Write, Bash\nmodel: sonnet\n---\nEscribe y ejecuta tests para el código nuevo.',
      },
    },
    tips: [
      'Roles con fronteras nítidas rinden más que muchos agentes solapados. Dos bien definidos baten a cinco difusos.',
      'Limita las tools de cada agente a lo que su rol necesita (un revisor no necesita escribir): además de más seguro, hace el organigrama legible.',
    ],
    commonMistakes: [
      'Escribir un agente sin la clave name en el frontmatter → el parser lo descarta y no cuenta. Necesitas name en cada fichero.',
      'Dejar un solo agente (agents = 1): T6 exige dos o más. Un único agente es todavía T5.',
      'Meter los ficheros fuera de .claude/agents/ → el parser está acotado a esa carpeta (en proyecto y en home, por el alcance proyecto ∪ home). Fuera de ahí no se ven.',
    ],
  },

  T6: {
    title: 'T6 → T7 · Multi-agente → Taller orquestado',
    upgradeWhen: '`hooks >= 1` (≥1 hook declarado en .claude/settings.json — scanner.js::countJsonKeys(settings.json, \'hooks\')).',
    unlocks: 'Automatización que se dispara sola en los momentos clave: un hook ejecuta lint antes de cada commit, o bloquea un comando peligroso sin que tengas que acordarte. El salto de "delego tareas a mis agentes" a "mi taller reacciona solo a lo que pasa".',
    steps: [
      { text: 'Elige un momento que quieras blindar (antes de commit, antes de ejecutar un comando, al terminar una tarea).', estimate: '5 min' },
      { text: 'Declara un hook para ese evento en .claude/settings.json.', estimate: '15-25 min' },
      { text: 'Provoca el evento y confirma que el hook se dispara como esperabas.', estimate: '10 min' },
    ],
    snippet: {
      language: 'json',
      label: '.claude/settings.json con un hook (la clave hooks con ≥1 entrada te sube a T7)',
      filename: '.claude/settings.json',
      code: '{\n  "hooks": {\n    "PreToolUse": [\n      {\n        "matcher": "Bash",\n        "hooks": [\n          { "type": "command", "command": "echo \'Revisa el comando antes de ejecutarlo\'" }\n        ]\n      }\n    ]\n  }\n}',
    },
    tips: [
      'Empieza por un hook defensivo (avisar o bloquear), no destructivo: aprendes el mecanismo sin riesgo.',
      'Un hook que se dispara siempre y estorba lo acabas desactivando. Acótalo con matcher a los casos que de verdad importan.',
    ],
    commonMistakes: [
      'Escribir la automatización como un script suelto en el repo en vez de declararla en settings.json → hoy el CLI cuenta hooks por la clave hooks del settings.json; un script suelto no es una categoría detectada todavía y no sube de tier.',
      'Dejar la clave hooks presente pero vacía → cuenta como 0, no sube.',
      'Un JSON con error de sintaxis en settings.json → el conteo devuelve 0 (el parser falla en silencio). Valida el JSON.',
    ],
  },
};

// T7 has no "next tier" — a distinct terminal shape (source doc: "Sin pasos
// de subida. No hay tier superior").
const T7_TERMINAL_ES = {
  title: 'T7 · Taller orquestado — nivel máximo',
  intro: 'Ya estás en el tier más alto de la escala. Tu setup combina multi-agente + MCP + assets propios + automatización por hooks: está equipado de arriba a abajo.',
  whatRemains: 'El tier ya no sube, pero el equipamiento no es el trabajo. A partir de aquí el margen está en usar lo que tienes, no en instalar más: documentar tu setup para que otros lo repliquen, podar lo que no usas, y afilar cada agente/comando con el trabajo real. La escala mide cómo tienes montado el banco; que salgan buenas piezas de él depende de ti.',
  consolidationSteps: [
    'Documenta tu organigrama de agentes y tus comandos para el resto del equipo.',
    'Revisa qué assets llevas tiempo sin tocar (el CLI expone recency/mtime de forma informativa, no como gate — ADR-003): quizá sobran.',
    'Comparte tu setup como referencia interna.',
  ],
  honestyNote: 'Estar en T7 significa que tienes el banco de trabajo mejor equipado que el CLI sabe medir. No significa que seas quien mejor usa la IA: el dato es una proxy de setup, indicativa y no verificada (ADR-007). No se lee como "calidad IA del Talent".',
};

// Only Spanish is authored today (see module header). No `en` catalog is
// invented — `getRoadmapEntry` reports `pendingTranslation: true` instead,
// so the render layer can show an honest notice rather than fabricate
// English prose for authored product content.
const CONTENT_BY_LANG = { es: { jumps: TIER_JUMPS_ES, terminal: T7_TERMINAL_ES } };

// Returns the roadmap entry for the CURRENT tier only (never the whole
// ladder), or `null` for an unrecognized tier key. `lang` selects the
// authored language if available; unauthored languages fall back to
// Spanish with `pendingTranslation: true` so the caller can render a
// notice instead of silently serving the "wrong" language.
function getRoadmapEntry(tierKey, lang = 'es') {
  const authored = CONTENT_BY_LANG[lang] ? lang : 'es';
  const pendingTranslation = authored !== lang;
  const catalog = CONTENT_BY_LANG[authored];

  if (tierKey === 'T7') {
    return { tierKey: 'T7', maxTier: true, lang: authored, pendingTranslation, ...catalog.terminal };
  }
  const jump = catalog.jumps[tierKey];
  if (!jump) return null;
  return { tierKey, maxTier: false, lang: authored, pendingTranslation, ...jump };
}

module.exports = { getRoadmapEntry, TIER_JUMPS_ES, T7_TERMINAL_ES };
