'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const http = require('http');
const https = require('https');

/*
 * Sharing layer.
 *
 * Principles:
 *  - The public code contains NO endpoint or secret. The URL it sends to
 *    arrives INSIDE the credential obtained at enrollment time.
 *  - Only a minimal, DERIVED payload is sent (booleans, counts, level).
 *    Never file contents, paths, or the talent's credentials.
 *  - talents-ai-score / ADR-005: the interactive preview + confirmation is
 *    removed. Sending is AUTOMATIC at the end of a normal run if there's a
 *    valid credential and the consent flag (persisted in the credential
 *    itself) is ON. "Building the mechanism is not activating it": the flag
 *    still exists precisely so sending can be turned off without touching
 *    code (in addition to the server kill switch — double switch, ADR-005).
 */

const CONFIG_DIR = path.join(os.homedir(), '.config', 'ai-footprint');
const CRED_PATH = path.join(CONFIG_DIR, 'credentials.json');

// Client-side throttle: don't retry a submission if the last one was less
// than 1h ago. Independent of the server's rate limit (that's enforced by
// the backend).
const SEND_THROTTLE_MS = 60 * 60 * 1000;

// DEFAULT of the consent flag persisted in the credential.
//
// ADR-006 (active-work/talents-ai-score/decisions.md) explicitly revises
// ADR-005's OFF default to ON: "the user decides that sending happens from
// the start, with no OFF defaults". The kill mechanism (this flag + the
// server kill switch) remains intact — only the default value changes. By
// its own caveat, ADR-006 IS the point of no return for ADR-005: it still
// requires legal/labor sign-off BEFORE deploying the backend and
// distributing the CLI (that deployment, not this code, is what kicks off
// the real data flow about real talents).
const DEFAULT_CONSENT = true;

/* ---------- minimal HTTP utility (no dependencies) ---------- */

function requestJson(method, url, { token, body } = {}) {
  return new Promise((resolve, reject) => {
    let u;
    try {
      u = new URL(url);
    } catch {
      return reject(new Error(`URL inválida: ${url}`));
    }
    const lib = u.protocol === 'https:' ? https : http;
    const data = body ? Buffer.from(JSON.stringify(body)) : null;
    const headers = { Accept: 'application/json' };
    if (data) {
      headers['Content-Type'] = 'application/json';
      headers['Content-Length'] = data.length;
    }
    if (token) headers['Authorization'] = `Bearer ${token}`;

    const req = lib.request(
      u,
      { method, headers, timeout: 15000 },
      (res) => {
        let raw = '';
        res.on('data', (c) => (raw += c));
        res.on('end', () => {
          let json = null;
          try { json = raw ? JSON.parse(raw) : null; } catch { /* non-JSON response */ }
          resolve({ status: res.statusCode, json, raw });
        });
      },
    );
    req.on('timeout', () => req.destroy(new Error('Tiempo de espera agotado')));
    req.on('error', reject);
    if (data) req.write(data);
    req.end();
  });
}

/* ---------- credentials ---------- */

function loadCredentials() {
  try {
    return JSON.parse(fs.readFileSync(CRED_PATH, 'utf8'));
  } catch {
    return null;
  }
}

function saveCredentials(cred) {
  fs.mkdirSync(CONFIG_DIR, { recursive: true });
  fs.writeFileSync(CRED_PATH, JSON.stringify(cred, null, 2));
  try { fs.chmodSync(CRED_PATH, 0o600); } catch { /* e.g. Windows */ }
}

/* ---------- consent ----------
 *
 * The flag lives in the local credential, not as a per-run argument
 * (specs.md #cli-changes-ai-usage-evaluator). Default ON (ADR-006).
 * `setConsent` is the mechanism to turn it off/on without re-enrolling or
 * touching code — needed to be able to revert to OFF (or to opt-in by
 * restoring the confirmation block in code) if the ADR-005/006 legal gate
 * requires it.
 */

function hasConsent(cred) {
  if (!cred) return false;
  return cred.consent === undefined ? DEFAULT_CONSENT : !!cred.consent;
}

function setConsent(enabled) {
  const cred = loadCredentials();
  if (!cred) {
    return {
      ok: false,
      reason: 'No estás enrolado. Enrólate primero con: ai-footprint --enroll=TU_CODIGO',
    };
  }
  cred.consent = !!enabled;
  saveCredentials(cred);
  return { ok: true, cred };
}

/* ---------- client-side throttle ---------- */

function isThrottled(cred, now = Date.now()) {
  if (!cred || !cred.lastSentAt) return false;
  const last = new Date(cred.lastSentAt).getTime();
  if (Number.isNaN(last)) return false;
  return now - last < SEND_THROTTLE_MS;
}

/* ---------- enrollment ---------- */

// The enrollment string is base64url of {enrollUrl, code}. It's generated by
// the platform panel, personalized per talent, with a single-use code.
function decodeEnrollString(str) {
  let obj;
  try {
    obj = JSON.parse(Buffer.from(str, 'base64url').toString('utf8'));
  } catch {
    throw new Error('Código de enrolamiento no válido o corrupto.');
  }
  if (!obj.enrollUrl || !obj.code) {
    throw new Error('El código de enrolamiento no contiene enrollUrl y code.');
  }
  return obj;
}

async function enroll(enrollString) {
  const { enrollUrl, code } = decodeEnrollString(enrollString.trim());
  const res = await requestJson('POST', enrollUrl, { body: { code } });

  if (res.status === 200 && res.json && res.json.token && res.json.endpoint) {
    const cred = {
      endpoint: res.json.endpoint,
      token: res.json.token,
      talentId: res.json.talentId || null,
      enrolledAt: new Date().toISOString(),
      expiresAt: res.json.expiresAt || null,
      consent: DEFAULT_CONSENT,
      lastSentAt: null,
    };
    saveCredentials(cred);
    return { ok: true, cred };
  }
  if (res.status === 409) return { ok: false, reason: 'Este código ya se ha usado.' };
  if (res.status === 404 || res.status === 400)
    return { ok: false, reason: 'Código no reconocido o caducado.' };
  return { ok: false, reason: `El servidor respondió ${res.status}.` };
}

/* ---------- derived payload (strict whitelist) ---------- */

// Only these fields leave the machine. Even if the report object grows in
// the future, what's shared is chosen explicitly here.
//
// PENDING DECISION (talents-ai-score, signal expansion — left to a human,
// "conservative default" per the brief): the local scan (scanner.js) now
// produces more per-tool fields (version, footprint, recency) and
// report-level fields (environment: platform/arch/nodeVersion/
// editorsInstalled). NONE of them have been added here yet. Proposal,
// field by field:
//
//   - tool.version                     -> Do NOT include by default.
//     Increases the ability to re-identify/correlate the machine across
//     submissions (a finer fingerprint than anonId) with no clear product
//     value in return.
//   - tool.footprint (bytes/files)     -> Low risk, similar sensitivity to
//     the depth counts already shared. Reasonable candidate to include, but
//     left to human judgment: it adds the talent's actual machine size,
//     which isn't as "pure" as a boolean/level.
//   - tool.recency (mtime/days/bucket) -> Do NOT include. It's the most
//     sensitive of the new signals: even though it's a derived date
//     (ADR-003), sending it turns "setup footprint" into "activity
//     monitoring" of how the talent works — the exact risk ADR-003
//     explicitly gated. Requires legal/GDPR review before even considering it.
//   - environment.arch / .nodeVersion  -> Low risk, useful to understand
//     the talent pool's machine landscape. Reasonable candidate.
//   - environment.editorsInstalled     -> Low-medium risk (adds another
//     fingerprinting dimension combined with anonId). Off by default.
//
// None of the above activates on its own: to include a field, add it here
// explicitly after a human decision (and document it in decisions.md if
// it's a cross-role decision, ADR).
function derivePayload(report, maturity) {
  return {
    schemaVersion: report.schemaVersion,
    generatedAt: report.generatedAt,
    anonId: report.anonId,
    platform: report.platform,
    level: maturity.level,
    levelName: maturity.name,
    score: maturity.score,
    totalDetected: report.summary.totalDetected,
    categories: report.summary.categories,
    tools: report.tools.map((t) => ({
      id: t.id,
      detected: t.detected,
      depth: t.depth || {},
    })),
  };
}

/* ---------- automatic sending ---------- */

// Silent sending: no preview or confirmation (ADR-005). Invoked at the end
// of a normal run. Never throws — any reason not to send, or any sending
// failure, resolves with { ok:false, ... }, never breaks the local report.
async function autoShare(report, maturity) {
  const cred = loadCredentials();
  if (!cred) return { ok: false, skipped: true, reason: 'not-enrolled' };
  if (cred.expiresAt && new Date(cred.expiresAt) < new Date()) {
    return { ok: false, skipped: true, reason: 'expired' };
  }
  if (!hasConsent(cred)) return { ok: false, skipped: true, reason: 'consent-off' };
  if (isThrottled(cred)) return { ok: false, skipped: true, reason: 'throttled' };

  const payload = derivePayload(report, maturity);

  let res;
  try {
    res = await requestJson('POST', cred.endpoint, { token: cred.token, body: payload });
  } catch (e) {
    // Network failure: doesn't break the local report.
    return { ok: false, skipped: false, reason: 'network-error', error: e.message };
  }

  if (res.status >= 200 && res.status < 300) {
    cred.lastSentAt = new Date().toISOString();
    saveCredentials(cred);
    return { ok: true, response: res.json };
  }
  if (res.status === 401) {
    return {
      ok: false,
      skipped: false,
      reason: 'unauthorized',
      notice: 'Tu credencial ya no es válida. Vuelve a enrolarte: ai-footprint --enroll=TU_CODIGO',
    };
  }
  if (res.status === 429) {
    return { ok: false, skipped: false, reason: 'rate-limited' };
  }
  return { ok: false, skipped: false, reason: `http-${res.status}` };
}

module.exports = {
  enroll,
  autoShare,
  setConsent,
  hasConsent,
  isThrottled,
  derivePayload,
  loadCredentials,
  CRED_PATH,
  SEND_THROTTLE_MS,
  DEFAULT_CONSENT,
};
