'use strict';

// Talent-facing copy of the MCP sign-up (ticket 39540, UX review 39574): fixed text the AI shows word for word, in the talent's language.

const SIGNUP_LANGUAGES = ['es', 'en', 'it', 'pt'];

// Legal texts. PENDING legal/GDPR validation: not final copy. The CLI onboarding reads the es/en ones too.
const LEGAL = {
  es: {
    signupNotice: 'Antes de crear tu cuenta: guardamos los datos que me des (tu LinkedIn, tu CV y lo que sé de ti) y podemos contactarte. Te completo el perfil automáticamente y cualquier campo lo puedes cambiar después en la web. La entrevista de onboarding la puedes hacer luego aquí mismo en el chat o en la web.',
    usageInfoAccessed: 'Se accede a: la estructura de tus herramientas de IA y a extractos anonimizados de tu actividad en este equipo. Tu código y tus prompts en crudo NUNCA salen de tu máquina.',
    usageGoalDuration: 'Objetivo: medir cómo trabajas con IA para tu perfil. Duración: ~1-2 minutos.',
    interviewInfoAccessed: 'Se accede a: tus respuestas en esta entrevista y tu perfil importado. La conduce el servidor de Shakers.',
    interviewGoalDuration: 'Objetivo: conocer tu rol, tu dedicación y cómo usas la IA. Duración: ~5 minutos.',
  },
  en: {
    signupNotice: 'Before we create your account: we store the data you give me (your LinkedIn, your CV and what I know about you) and may contact you. I fill in your profile automatically and you can change any field later on the web. You can do the onboarding interview afterwards right here in the chat or on the web.',
    usageInfoAccessed: 'Accessed: the structure of your AI tools and redacted excerpts of your activity on this machine. Your raw code and prompts NEVER leave your machine.',
    usageGoalDuration: 'Goal: measure how you work with AI for your profile. Duration: ~1-2 minutes.',
    interviewInfoAccessed: 'Accessed: your answers in this interview and your imported profile. It is conducted by the Shakers server.',
    interviewGoalDuration: 'Goal: learn your role, your dedication and how you use AI. Duration: ~5 minutes.',
  },
  it: {
    signupNotice: 'Prima di creare il tuo account: conserviamo i dati che mi dai (il tuo LinkedIn, il tuo CV e quello che so di te) e possiamo contattarti. Completo il tuo profilo in automatico e puoi cambiare qualsiasi campo in seguito sul sito. Il colloquio di onboarding puoi farlo dopo qui nella chat o sul sito.',
    usageInfoAccessed: 'Accesso a: la struttura dei tuoi strumenti di IA ed estratti anonimizzati della tua attività su questo computer. Il tuo codice e i tuoi prompt originali NON escono MAI dalla tua macchina.',
    usageGoalDuration: "Obiettivo: misurare come lavori con l'IA per il tuo profilo. Durata: ~1-2 minuti.",
    interviewInfoAccessed: 'Accesso a: le tue risposte in questo colloquio e il tuo profilo importato. Lo conduce il server di Shakers.',
    interviewGoalDuration: "Obiettivo: conoscere il tuo ruolo, la tua disponibilità e come usi l'IA. Durata: ~5 minuti.",
  },
  pt: {
    signupNotice: 'Antes de criar a sua conta: guardamos os dados que me der (o seu LinkedIn, o seu CV e o que sei sobre si) e podemos contactá-lo. Preencho o seu perfil automaticamente e pode alterar qualquer campo depois na web. A entrevista de onboarding pode fazê-la depois aqui mesmo no chat ou na web.',
    usageInfoAccessed: 'Acede-se a: a estrutura das suas ferramentas de IA e excertos anonimizados da sua atividade neste computador. O seu código e os seus prompts em bruto NUNCA saem da sua máquina.',
    usageGoalDuration: 'Objetivo: medir como trabalha com IA para o seu perfil. Duração: ~1-2 minutos.',
    interviewInfoAccessed: 'Acede-se a: as suas respostas nesta entrevista e o seu perfil importado. É conduzida pelo servidor da Shakers.',
    interviewGoalDuration: 'Objetivo: conhecer o seu perfil, a sua dedicação e como usa a IA. Duração: ~5 minutos.',
  },
};

const LOCALES = { es: 'es-ES', en: 'en-GB', it: 'it-IT', pt: 'pt-PT' };

function joinParts(parts) {
  return parts.filter((p) => p !== null && p !== undefined && String(p).trim() !== '').join(' · ');
}

function amount(lang, value) {
  return new Intl.NumberFormat(LOCALES[lang], { maximumFractionDigits: 0 }).format(Number(value));
}

const COPY = {
  es: {
    welcome: (name) => `¡Hola${name ? `, ${name}` : ''}! Gracias por querer unirte a Shakers 🙌\n\nSomos una comunidad de profesionales tech freelance. Nuestro objetivo es tener siempre tu versión más actual como profesional (lo que sabes hacer hoy, cómo trabajas con IA y qué buscas) para conectarte con proyectos que de verdad encajen contigo.\n\nEl alta son tres pasos y la mayor parte la hago yo por ti:\n1. Tu perfil (2 min). Lo relleno a partir de tu CV y LinkedIn, tú solo revisas y confirmas.\n2. Cómo trabajas con IA (1-2 min, opcional). Analizo qué herramientas usas en este equipo. Tu código y tus prompts nunca salen de tu máquina.\n3. Una breve entrevista (opcional). Para afinar tu rol y lo que buscas. Puedes hacerla ahora o más tarde.\n\nTodo lo puedes editar después desde la web.`,
    welcomeQuestion: '¿Empezamos? Si me das permiso, busco tu CV en este equipo y te preparo un borrador para que solo tengas que confirmarlo.',
    cvSearch: 'Sí, búscalo',
    cvAttach: 'Te lo adjunto yo',
    cvAttachAsk: 'Perfecto, adjúntamelo aquí.',
    cvNotFound: 'No he encontrado tu CV en este equipo. ¿Me lo adjuntas aquí?',
    linkedinAsk: '¿Me pasas tu perfil de LinkedIn?',
    linkedinOpening: 'Te abro tu perfil de LinkedIn en el navegador para que copies la dirección.',
    linkedinOpened: 'Te he abierto tu perfil de LinkedIn; copia la dirección de la barra y pégamela aquí.',
    emailKnown: (email) => `¿Te registro con ${email}? Usa el email que más mires: ahí te llegarán los proyectos que encajen contigo y las novedades de Shakers.`,
    emailUnknown: '¿Con qué email te registro? Usa el que más mires: ahí te llegarán los proyectos que encajen contigo y las novedades de Shakers.',
    emailWorkHint: 'Si es el de tu trabajo actual, quizá prefieras uno personal para no perder el acceso si cambias de empresa.',
    emailYes: 'Sí, ese',
    emailOther: 'Usar otro',
    draftTitle: 'Esto es lo que he preparado para tu perfil:',
    years: (n) => `${n} años de experiencia`,
    hours: (h) => `${h} h/mes`,
    rates: (hourly, annual) => `Tarifa estimada: ${joinParts([hourly != null ? `${amount('es', hourly)} €/h` : null, annual != null ? `${amount('es', annual)} €/año` : null])} (estimación mía, ajústala)`,
    draftQuestion: '¿Está bien o cambio algo?',
    draftOk: 'Todo correcto',
    draftChange: 'Quiero cambiar algo',
    windowOpening: 'Perfecto. Ahora solo falta crear tu cuenta para guardar todo esto y que puedas entrar en Shakers cuando quieras.\n\nTe abro una ventana en el navegador, elige cómo entrar:\n· Con Google\n· Con email y contraseña\n\nLa contraseña la escribes allí directamente, nunca pasa por este chat. En esa misma pantalla aceptas los términos y la política de privacidad.\n\n👉 Mira tu navegador. Cuando termines, vuelve aquí y seguimos.',
    windowLink: (link) => `Si no se te ha abierto la ventana, entra desde aquí: ${link}`,
    existingTitle: 'He visto que ya tienes cuenta. ¿Actualizo tu perfil con esto?',
    existingRate: (from, to) => `Tarifa por hora: ${from} → ${to}`,
    existingAnnual: (from, to) => `Tarifa anual: ${from} → ${to}`,
    existingHours: (from, to) => `Disponibilidad: ${from} → ${to}`,
    existingEmpty: 'sin indicar',
    existingLists: 'Añado lo nuevo de tu CV y tu LinkedIn (experiencias, proyectos, formación) y relleno lo que tengas vacío, sin borrar nada.',
    existingYes: 'Sí, actualízalo',
    existingNo: 'No, déjalo como está',
    existingKept: 'Perfecto, dejo tu perfil como está.',
    aiUsageQuestion: '¿Quieres que analice cómo trabajas con IA? Es opcional y tarda 1-2 min. Solo veo qué herramientas usas, tu código y tus prompts no salen de tu máquina. Te ayuda a destacar en proyectos de IA.',
    aiUsageYes: 'Sí, analízalo',
    aiUsageSkip: 'Saltar este paso',
    aiUsageSkipped: "Sin problema, seguimos sin él. Te aviso de que es lo que más pesa para que te lleguen proyectos: lo puedes lanzar cuando quieras diciéndome 'analiza mi uso de IA'.",
    interviewWhereQuestion: '¿Hacemos la entrevista de onboarding aquí ahora o luego en la web?',
    interviewHere: 'Aquí ahora',
    interviewLater: 'Luego en la web',
    answerModeQuestion: '¿Te propongo yo las respuestas con lo que sé de ti, o las contestas tú?',
    answerModeDrafted: 'Propónmelas tú',
    answerModeOwn: 'Las contesto yo',
    answerModeFull: 'Hazla entera',
    livekitUnavailable: 'La entrevista no puede arrancar en este equipo. Puedes hacerla en la web: te abro Shakers con tu sesión iniciada.',
    rolesIntro: 'Con todo lo que me has contado, encajas en estos perfiles:',
    roleRecommended: (name) => `**${name}** (recomendado)`,
    roleName: (name) => `**${name}**`,
    roleReason: { IMPORT: 'Por tu CV y tu LinkedIn', ONBOARDING_INTERVIEW: 'Por lo que me contaste en la entrevista', MATCH: 'Por tu perfil en Shakers' },
    openProjects: (n) => (n === 1 ? 'Ahora mismo hay 1 proyecto abierto que busca este perfil.' : `Ahora mismo hay ${n} proyectos abiertos que buscan este perfil.`),
    rolesOutro: 'Tu perfil principal es el que ven primero las empresas y el que usamos para recomendarte proyectos. Puedes añadir más y cambiarlo cuando quieras.',
    mainRoleQuestion: '¿Cuál es tu perfil principal?',
    mainRoleOther: 'Otro rol del catálogo',
    hourlyRateLabel: 'Tarifa por hora',
    annualRateLabel: 'Tarifa anual',
    perHour: '€/h',
    perYear: '€/año',
    ratesSaved: (rates) => `${rates.join(' · ')}. Es una estimación: la puedes cambiar en la web.`,
    saved: { workSituation: 'Situación laboral guardada.', availability: 'Disponibilidad guardada.', languages: 'Idiomas guardados.', phone: 'Teléfono guardado.' },
    yes: 'Sí',
    no: 'No',
  },
  en: {
    welcome: (name) => `Hi${name ? `, ${name}` : ''}! Thanks for wanting to join Shakers 🙌\n\nWe are a community of freelance tech professionals. Our goal is to always have the most up-to-date version of you as a professional (what you can do today, how you work with AI and what you are looking for) to connect you with projects that truly fit you.\n\nSigning up takes three steps and I do most of it for you:\n1. Your profile (2 min). I fill it in from your CV and LinkedIn; you just review and confirm.\n2. How you work with AI (1-2 min, optional). I look at which tools you use on this computer. Your code and your prompts never leave your machine.\n3. A short interview (optional). To fine-tune your role and what you are looking for. You can do it now or later.\n\nYou can edit everything later on the web.`,
    welcomeQuestion: "Shall we start? With your permission, I'll look for your CV on this computer and prepare a draft so you only have to confirm it.",
    cvSearch: 'Yes, look for it',
    cvAttach: "I'll attach it",
    cvAttachAsk: 'Great, attach it here.',
    cvNotFound: "I couldn't find your CV on this computer. Could you attach it here?",
    linkedinAsk: 'Could you send me your LinkedIn profile?',
    linkedinOpening: 'I am opening your LinkedIn profile in your browser so you can copy its address.',
    linkedinOpened: 'I have opened your LinkedIn profile; copy the address from the address bar and paste it here.',
    emailKnown: (email) => `Shall I sign you up with ${email}? Use the email you check most: that is where the projects that fit you and Shakers news will arrive.`,
    emailUnknown: 'Which email shall I sign you up with? Use the one you check most: that is where the projects that fit you and Shakers news will arrive.',
    emailWorkHint: 'If it is your current work email, you may prefer a personal one so you do not lose access if you change companies.',
    emailYes: 'Yes, that one',
    emailOther: 'Use another one',
    draftTitle: 'Here is what I have prepared for your profile:',
    years: (n) => `${n} years of experience`,
    hours: (h) => `${h} h/month`,
    rates: (hourly, annual) => `Estimated rate: ${joinParts([hourly != null ? `${amount('en', hourly)} €/h` : null, annual != null ? `${amount('en', annual)} €/year` : null])} (my estimate, adjust it)`,
    draftQuestion: 'Does it look right, or shall I change something?',
    draftOk: 'All correct',
    draftChange: 'I want to change something',
    windowOpening: "Great. Now all that's left is to create your account, to save all this and so you can sign in to Shakers whenever you like.\n\nI'm opening a window in your browser; choose how to sign in:\n· With Google\n· With email and password\n\nYou type the password there directly; it never goes through this chat. On that same screen you accept the terms and the privacy policy.\n\n👉 Check your browser. When you're done, come back here and we'll carry on.",
    windowLink: (link) => `If the window did not open, use this link: ${link}`,
    existingTitle: 'I see you already have an account. Shall I update your profile with this?',
    existingRate: (from, to) => `Hourly rate: ${from} → ${to}`,
    existingAnnual: (from, to) => `Annual rate: ${from} → ${to}`,
    existingHours: (from, to) => `Availability: ${from} → ${to}`,
    existingEmpty: 'not set',
    existingLists: 'I add what is new from your CV and LinkedIn (experience, projects, education) and fill in what is empty, without deleting anything.',
    existingYes: 'Yes, update it',
    existingNo: 'No, leave it as it is',
    existingKept: 'Sure, I am leaving your profile as it is.',
    aiUsageQuestion: 'Do you want me to analyse how you work with AI? It is optional and takes 1-2 min. I only see which tools you use; your code and your prompts do not leave your machine. It helps you stand out for AI projects.',
    aiUsageYes: 'Yes, analyse it',
    aiUsageSkip: 'Skip this step',
    aiUsageSkipped: "No problem, we carry on without it. Heads-up: it is what weighs most for projects to reach you. You can run it whenever you like by telling me 'analyse my AI usage'.",
    interviewWhereQuestion: 'Shall we do the onboarding interview here now or later on the web?',
    interviewHere: 'Here now',
    interviewLater: 'Later on the web',
    answerModeQuestion: 'Shall I draft your answers from what I know about you, or will you answer yourself?',
    answerModeDrafted: 'Draft them for me',
    answerModeOwn: "I'll answer myself",
    answerModeFull: 'Do it all for me',
    livekitUnavailable: 'The interview cannot start on this machine. You can do it on the web: I will open Shakers with you signed in.',
    rolesIntro: 'With everything you have told me, you fit these profiles:',
    roleRecommended: (name) => `**${name}** (recommended)`,
    roleName: (name) => `**${name}**`,
    roleReason: { IMPORT: 'From your CV and LinkedIn', ONBOARDING_INTERVIEW: 'From what you told me in the interview', MATCH: 'From your Shakers profile' },
    openProjects: (n) => (n === 1 ? 'Right now there is 1 open project looking for this profile.' : `Right now there are ${n} open projects looking for this profile.`),
    rolesOutro: 'Your main profile is the one companies see first and the one we use to recommend projects to you. You can add more and change it whenever you like.',
    mainRoleQuestion: 'Which is your main profile?',
    mainRoleOther: 'Another role from the catalogue',
    hourlyRateLabel: 'Hourly rate',
    annualRateLabel: 'Annual rate',
    perHour: '€/hour',
    perYear: '€/year',
    ratesSaved: (rates) => `${rates.join(' · ')}. It is an estimate: you can change it on the web.`,
    saved: { workSituation: 'Work situation saved.', availability: 'Availability saved.', languages: 'Languages saved.', phone: 'Phone saved.' },
    yes: 'Yes',
    no: 'No',
  },
  it: {
    welcome: (name) => `Ciao${name ? `, ${name}` : ''}! Grazie per voler entrare in Shakers 🙌\n\nSiamo una community di professionisti tech freelance. Il nostro obiettivo è avere sempre la tua versione più aggiornata come professionista (cosa sai fare oggi, come lavori con l'IA e cosa cerchi) per metterti in contatto con progetti che fanno davvero per te.\n\nL'iscrizione richiede tre passaggi e la maggior parte la faccio io per te:\n1. Il tuo profilo (2 min). Lo compilo a partire dal tuo CV e da LinkedIn, tu devi solo rivederlo e confermarlo.\n2. Come lavori con l'IA (1-2 min, facoltativo). Analizzo quali strumenti usi su questo computer. Il tuo codice e i tuoi prompt non escono mai dalla tua macchina.\n3. Un breve colloquio (facoltativo). Per definire meglio il tuo ruolo e cosa cerchi. Puoi farlo ora o più tardi.\n\nPuoi modificare tutto in seguito dal sito.`,
    welcomeQuestion: 'Iniziamo? Se mi dai il permesso, cerco il tuo CV su questo computer e ti preparo una bozza da confermare e basta.',
    cvSearch: 'Sì, cercalo',
    cvAttach: 'Te lo allego io',
    cvAttachAsk: 'Perfetto, allegalo qui.',
    cvNotFound: 'Non ho trovato il tuo CV su questo computer. Me lo alleghi qui?',
    linkedinAsk: 'Mi mandi il tuo profilo LinkedIn?',
    linkedinOpening: "Ti apro il tuo profilo LinkedIn nel browser così puoi copiarne l'indirizzo.",
    linkedinOpened: "Ti ho aperto il tuo profilo LinkedIn; copia l'indirizzo dalla barra e incollalo qui.",
    emailKnown: (email) => `Ti registro con ${email}? Usa l'email che controlli di più: lì ti arriveranno i progetti adatti a te e le novità di Shakers.`,
    emailUnknown: "Con quale email ti registro? Usa quella che controlli di più: lì ti arriveranno i progetti adatti a te e le novità di Shakers.",
    emailWorkHint: "Se è quella del tuo lavoro attuale, forse ne preferisci una personale per non perdere l'accesso se cambi azienda.",
    emailYes: 'Sì, quella',
    emailOther: "Usane un'altra",
    draftTitle: 'Ecco cosa ho preparato per il tuo profilo:',
    years: (n) => `${n} anni di esperienza`,
    hours: (h) => `${h} h/mese`,
    rates: (hourly, annual) => `Tariffa stimata: ${joinParts([hourly != null ? `${amount('it', hourly)} €/h` : null, annual != null ? `${amount('it', annual)} €/anno` : null])} (una mia stima, modificala pure)`,
    draftQuestion: 'Va bene o cambio qualcosa?',
    draftOk: 'Tutto corretto',
    draftChange: 'Voglio cambiare qualcosa',
    windowOpening: "Perfetto. Ora manca solo creare il tuo account per salvare tutto questo e poter entrare in Shakers quando vuoi.\n\nTi apro una finestra nel browser, scegli come entrare:\n· Con Google\n· Con email e password\n\nLa password la scrivi direttamente lì, non passa mai da questa chat. Nella stessa schermata accetti i termini e l'informativa sulla privacy.\n\n👉 Guarda il tuo browser. Quando hai finito, torna qui e continuiamo.",
    windowLink: (link) => `Se la finestra non si è aperta, entra da qui: ${link}`,
    existingTitle: 'Ho visto che hai già un account. Aggiorno il tuo profilo con questi dati?',
    existingRate: (from, to) => `Tariffa oraria: ${from} → ${to}`,
    existingAnnual: (from, to) => `Tariffa annuale: ${from} → ${to}`,
    existingHours: (from, to) => `Disponibilità: ${from} → ${to}`,
    existingEmpty: 'non indicata',
    existingLists: 'Aggiungo le novità del tuo CV e di LinkedIn (esperienze, progetti, formazione) e compilo quello che hai vuoto, senza cancellare nulla.',
    existingYes: 'Sì, aggiornalo',
    existingNo: 'No, lascialo così',
    existingKept: 'Perfetto, lascio il tuo profilo così com’è.',
    aiUsageQuestion: "Vuoi che analizzi come lavori con l'IA? È facoltativo e richiede 1-2 min. Vedo solo quali strumenti usi, il tuo codice e i tuoi prompt non escono dalla tua macchina. Ti aiuta a distinguerti nei progetti di IA.",
    aiUsageYes: 'Sì, analizzalo',
    aiUsageSkip: 'Salta questo passaggio',
    aiUsageSkipped: "Nessun problema, andiamo avanti senza. Ti avviso che è ciò che pesa di più perché ti arrivino progetti: puoi lanciarlo quando vuoi dicendomi 'analizza il mio uso dell'IA'.",
    interviewWhereQuestion: 'Facciamo il colloquio di onboarding qui adesso o più tardi sul sito?',
    interviewHere: 'Qui adesso',
    interviewLater: 'Più tardi sul sito',
    answerModeQuestion: 'Ti propongo io le risposte con quello che so di te, o rispondi tu?',
    answerModeDrafted: 'Proponile tu',
    answerModeOwn: 'Rispondo io',
    answerModeFull: 'Fallo tutto tu',
    livekitUnavailable: 'Il colloquio non può partire su questo computer. Puoi farlo sul sito: ti apro Shakers con la sessione già avviata.',
    rolesIntro: 'Con tutto quello che mi hai raccontato, sei adatto a questi profili:',
    roleRecommended: (name) => `**${name}** (consigliato)`,
    roleName: (name) => `**${name}**`,
    roleReason: { IMPORT: 'Dal tuo CV e da LinkedIn', ONBOARDING_INTERVIEW: 'Da quello che mi hai raccontato nel colloquio', MATCH: 'Dal tuo profilo su Shakers' },
    openProjects: (n) => (n === 1 ? "In questo momento c'è 1 progetto aperto che cerca questo profilo." : `In questo momento ci sono ${n} progetti aperti che cercano questo profilo.`),
    rolesOutro: 'Il tuo profilo principale è quello che le aziende vedono per primo e quello che usiamo per consigliarti progetti. Puoi aggiungerne altri e cambiarlo quando vuoi.',
    mainRoleQuestion: 'Qual è il tuo profilo principale?',
    mainRoleOther: 'Un altro ruolo del catalogo',
    hourlyRateLabel: 'Tariffa oraria',
    annualRateLabel: 'Tariffa annuale',
    perHour: '€/h',
    perYear: '€/anno',
    ratesSaved: (rates) => `${rates.join(' · ')}. È una stima: puoi cambiarla sul sito.`,
    saved: { workSituation: 'Situazione lavorativa salvata.', availability: 'Disponibilità salvata.', languages: 'Lingue salvate.', phone: 'Telefono salvato.' },
    yes: 'Sì',
    no: 'No',
  },
  pt: {
    welcome: (name) => `Olá${name ? `, ${name}` : ''}! Obrigado por querer juntar-se à Shakers 🙌\n\nSomos uma comunidade de profissionais tech freelance. O nosso objetivo é ter sempre a sua versão mais atual como profissional (o que sabe fazer hoje, como trabalha com IA e o que procura) para o pôr em contacto com projetos que encaixem mesmo consigo.\n\nO registo tem três passos e a maior parte faço eu por si:\n1. O seu perfil (2 min). Preencho-o a partir do seu CV e do LinkedIn; só tem de rever e confirmar.\n2. Como trabalha com IA (1-2 min, opcional). Analiso que ferramentas usa neste computador. O seu código e os seus prompts nunca saem da sua máquina.\n3. Uma breve entrevista (opcional). Para afinar o seu perfil e o que procura. Pode fazê-la agora ou mais tarde.\n\nPode editar tudo depois na web.`,
    welcomeQuestion: 'Começamos? Se me der autorização, procuro o seu CV neste computador e preparo um rascunho para que só tenha de o confirmar.',
    cvSearch: 'Sim, procure-o',
    cvAttach: 'Eu anexo-o',
    cvAttachAsk: 'Perfeito, anexe-o aqui.',
    cvNotFound: 'Não encontrei o seu CV neste computador. Pode anexá-lo aqui?',
    linkedinAsk: 'Pode enviar-me o seu perfil do LinkedIn?',
    linkedinOpening: 'Vou abrir o seu perfil do LinkedIn no navegador para que copie o endereço.',
    linkedinOpened: 'Abri o seu perfil do LinkedIn; copie o endereço da barra e cole-o aqui.',
    emailKnown: (email) => `Registo-o com ${email}? Use o email que consulta mais: é aí que vai receber os projetos que encaixam consigo e as novidades da Shakers.`,
    emailUnknown: 'Com que email o registo? Use o que consulta mais: é aí que vai receber os projetos que encaixam consigo e as novidades da Shakers.',
    emailWorkHint: 'Se for o do seu trabalho atual, talvez prefira um pessoal para não perder o acesso se mudar de empresa.',
    emailYes: 'Sim, esse',
    emailOther: 'Usar outro',
    draftTitle: 'Isto é o que preparei para o seu perfil:',
    years: (n) => `${n} anos de experiência`,
    hours: (h) => `${h} h/mês`,
    rates: (hourly, annual) => `Tarifa estimada: ${joinParts([hourly != null ? `${amount('pt', hourly)} €/h` : null, annual != null ? `${amount('pt', annual)} €/ano` : null])} (estimativa minha, ajuste-a)`,
    draftQuestion: 'Está bem ou mudo alguma coisa?',
    draftOk: 'Está tudo certo',
    draftChange: 'Quero mudar algo',
    windowOpening: 'Perfeito. Agora só falta criar a sua conta para guardar tudo isto e poder entrar na Shakers quando quiser.\n\nVou abrir uma janela no seu navegador; escolha como entrar:\n· Com Google\n· Com email e palavra-passe\n\nEscreve a palavra-passe diretamente lá; nunca passa por este chat. Nesse mesmo ecrã aceita os termos e a política de privacidade.\n\n👉 Veja o seu navegador. Quando terminar, volte aqui e continuamos.',
    windowLink: (link) => `Se a janela não abriu, entre por aqui: ${link}`,
    existingTitle: 'Vi que já tem conta. Atualizo o seu perfil com isto?',
    existingRate: (from, to) => `Tarifa por hora: ${from} → ${to}`,
    existingAnnual: (from, to) => `Tarifa anual: ${from} → ${to}`,
    existingHours: (from, to) => `Disponibilidade: ${from} → ${to}`,
    existingEmpty: 'sem indicar',
    existingLists: 'Acrescento o que há de novo no seu CV e no LinkedIn (experiências, projetos, formação) e preencho o que tiver vazio, sem apagar nada.',
    existingYes: 'Sim, atualize',
    existingNo: 'Não, deixe como está',
    existingKept: 'Perfeito, deixo o seu perfil como está.',
    aiUsageQuestion: 'Quer que analise como trabalha com IA? É opcional e demora 1-2 min. Só vejo que ferramentas usa; o seu código e os seus prompts não saem da sua máquina. Ajuda-o a destacar-se em projetos de IA.',
    aiUsageYes: 'Sim, analise',
    aiUsageSkip: 'Saltar este passo',
    aiUsageSkipped: "Sem problema, seguimos sem ele. Aviso-o de que é o que mais pesa para lhe chegarem projetos: pode lançá-lo quando quiser dizendo-me 'analisa o meu uso de IA'.",
    interviewWhereQuestion: 'Fazemos a entrevista de onboarding aqui agora ou mais tarde na web?',
    interviewHere: 'Aqui agora',
    interviewLater: 'Mais tarde na web',
    answerModeQuestion: 'Proponho-lhe eu as respostas com o que sei sobre si, ou responde você?',
    answerModeDrafted: 'Proponha-as você',
    answerModeOwn: 'Respondo eu',
    answerModeFull: 'Faça-a toda',
    livekitUnavailable: 'A entrevista não pode começar neste computador. Pode fazê-la na web: abro-lhe a Shakers com a sessão iniciada.',
    rolesIntro: 'Com tudo o que me contou, encaixa nestes perfis:',
    roleRecommended: (name) => `**${name}** (recomendado)`,
    roleName: (name) => `**${name}**`,
    roleReason: { IMPORT: 'Pelo seu CV e pelo LinkedIn', ONBOARDING_INTERVIEW: 'Pelo que me contou na entrevista', MATCH: 'Pelo seu perfil na Shakers' },
    openProjects: (n) => (n === 1 ? 'Neste momento há 1 projeto aberto que procura este perfil.' : `Neste momento há ${n} projetos abertos que procuram este perfil.`),
    rolesOutro: 'O seu perfil principal é o que as empresas veem primeiro e o que usamos para lhe recomendar projetos. Pode adicionar mais e alterá-lo quando quiser.',
    mainRoleQuestion: 'Qual é o seu perfil principal?',
    mainRoleOther: 'Outro perfil do catálogo',
    hourlyRateLabel: 'Tarifa por hora',
    annualRateLabel: 'Tarifa anual',
    perHour: '€/h',
    perYear: '€/ano',
    ratesSaved: (rates) => `${rates.join(' · ')}. É uma estimativa: pode alterá-la na web.`,
    saved: { workSituation: 'Situação profissional guardada.', availability: 'Disponibilidade guardada.', languages: 'Idiomas guardados.', phone: 'Telefone guardado.' },
    yes: 'Sim',
    no: 'Não',
  },
};

function toSignupLanguage(code) {
  const base = String(code || '').toLowerCase().split(/[-_]/)[0];
  return SIGNUP_LANGUAGES.includes(base) ? base : null;
}

function signupCopy(lang) {
  return COPY[toSignupLanguage(lang) || 'en'];
}

function legalCopy(lang) {
  return LEGAL[toSignupLanguage(lang) || 'en'];
}

// The profile draft the talent confirms before the account exists: one line per group, empty parts left out.
function renderDraft(lang, d = {}) {
  const c = signupCopy(lang);
  const has = (v) => v !== null && v !== undefined && String(v).trim() !== '';
  const lines = [
    joinParts([d.name, d.role, d.city]),
    joinParts([has(d.yearsOfExperience) ? c.years(d.yearsOfExperience) : null, d.stack]),
    joinParts([d.languages, d.workMode, has(d.monthlyHours) ? c.hours(d.monthlyHours) : null]),
    has(d.hourlyRate) || has(d.annualRate) ? c.rates(has(d.hourlyRate) ? d.hourlyRate : null, has(d.annualRate) ? d.annualRate : null) : '',
  ].filter(Boolean);
  return [c.draftTitle, ...lines].join('\n');
}

// One role of the main-role step: name, why it fits (source + one fact) and, when known, how many open projects want it.
function renderRole(lang, { name, source, evidence, openProjects, recommended }) {
  const c = signupCopy(lang);
  const reason = c.roleReason[source] || null;
  const why = reason && evidence ? `${reason}: ${evidence}` : reason || evidence || null;
  return [
    recommended ? c.roleRecommended(name) : c.roleName(name),
    why,
    typeof openProjects === 'number' && openProjects > 0 ? c.openProjects(openProjects) : null,
  ].filter(Boolean).join('\n');
}

module.exports = { SIGNUP_LANGUAGES, LEGAL, signupCopy, legalCopy, toSignupLanguage, renderDraft, renderRole, amount };
