'use strict';

const fs = require('fs');
const path = require('path');

const { extensionsForTechnology } = require('./tech-extensions');

/*
 * Deterministic code SAMPLER for the certify phase (skill-code-certification,
 * issue 005 / ADR-001). Given a Talent's selected certifiable Skills (each
 * tied to a detected technology), it picks which project files to send for
 * LLM assessment — reproducibly and within strict token caps, so egress is
 * the minimum necessary and never a surprise.
 *
 * Rules (ADR-001 / specs.md "AI/LLM"):
 *   - Candidates = files whose extension is in the technology's map
 *     (src/tech-extensions.js). No mapping -> NOT sampleable (documented,
 *     never invented).
 *   - Exclusions: build/vendor dirs (node_modules, dist, build, .git, vendor,
 *     coverage, .next, out), lockfiles, *.min.*, *.map, and files that look
 *     machine-GENERATED by a header heuristic.
 *   - Order: size DESC, then path ASC (lexicographic) — fully deterministic,
 *     so the same tree always yields the same sample.
 *   - Budget: estTokens ~= bytes/4; cap ~50k tokens/Skill and ~150k/run.
 *   - SamplingMeta declares candidateCount/includedCount/estTokens/
 *     truncated/capReason so the report can warn "partial sample" — never a
 *     silent truncation.
 *
 * This module does NOT scrub or send — the caller (bin/certify.js) applies
 * scrubSecrets per file and builds the certify request. Kept pure/side-effect
 * -free (only reads the filesystem) so determinism is directly testable.
 */

const PER_SKILL_TOKEN_CAP = 50000;
const RUN_TOKEN_BUDGET = 150000;
const GENERATED_HEAD_BYTES = 512;

const EXCLUDED_DIRS = new Set([
  'node_modules', 'dist', 'build', '.git', 'vendor', 'coverage', '.next', 'out',
]);

const LOCKFILES = new Set([
  'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'npm-shrinkwrap.json',
  'poetry.lock', 'Pipfile.lock', 'Gemfile.lock', 'composer.lock', 'go.sum', 'Cargo.lock',
]);

// Heuristic marker of machine-generated files (checked against the file head).
const GENERATED_RE = /@generated|@auto-generated|DO NOT EDIT|auto-?generated|Code generated by/i;

function estTokensFor(bytes) {
  return Math.ceil((bytes || 0) / 4);
}

function readFileSafe(abspath) {
  try {
    return fs.readFileSync(abspath, 'utf8');
  } catch {
    return null;
  }
}

// Reads only the first bytes for the generated-file heuristic, so huge
// generated files aren't fully read just to be excluded.
function readHead(abspath, n = GENERATED_HEAD_BYTES) {
  let fd;
  try {
    fd = fs.openSync(abspath, 'r');
    const buf = Buffer.alloc(n);
    const bytesRead = fs.readSync(fd, buf, 0, n, 0);
    return buf.toString('utf8', 0, bytesRead);
  } catch {
    return '';
  } finally {
    if (fd !== undefined) { try { fs.closeSync(fd); } catch { /* ignore */ } }
  }
}

function isExcludedFileName(name) {
  if (LOCKFILES.has(name)) return true;
  if (/\.min\./.test(name)) return true;
  if (name.endsWith('.map')) return true;
  return false;
}

function hasMatchingExtension(name, extensions) {
  const lower = name.toLowerCase();
  return extensions.some((ext) => lower.endsWith(ext));
}

// Walks `root`, returns candidate files {path (relative, POSIX-ish), abspath,
// bytes} matching `extensions`, excluding build/vendor dirs, lockfiles,
// minified/map/generated files. Sorted size DESC then path ASC.
function listCandidateFiles(root, extensions) {
  const out = [];

  function walk(dir, rel) {
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const name = entry.name;
      const abs = path.join(dir, name);
      const relPath = rel ? `${rel}/${name}` : name;
      if (entry.isDirectory()) {
        if (EXCLUDED_DIRS.has(name)) continue;
        walk(abs, relPath);
      } else if (entry.isFile()) {
        if (isExcludedFileName(name)) continue;
        if (!hasMatchingExtension(name, extensions)) continue;
        let bytes;
        try {
          bytes = fs.statSync(abs).size;
        } catch {
          continue;
        }
        if (GENERATED_RE.test(readHead(abs))) continue;
        out.push({ path: relPath, abspath: abs, bytes });
      }
    }
  }

  walk(root, '');

  out.sort((a, b) => {
    if (b.bytes !== a.bytes) return b.bytes - a.bytes; // size DESC
    return a.path < b.path ? -1 : a.path > b.path ? 1 : 0; // path ASC (lexicographic)
  });
  return out;
}

function notSampleableMeta(technology) {
  return {
    technology,
    extensions: null,
    sampleable: false,
    candidateCount: 0,
    includedCount: 0,
    totalBytes: 0,
    estTokens: 0,
    truncated: false,
    capReason: null,
  };
}

// Samples the selected Skills. `selections` = [{skillId, skillName,
// technology}]. Processed in a deterministic order (skillId ASC, then
// skillName) so the shared run budget is distributed reproducibly regardless
// of the order the talent selected them in. Returns, per selection,
// {skillId, skillName, technology, files:[{path, content, bytes, estTokens}],
// meta: SamplingMeta}.
function buildSkillSamples(root, selections, opts = {}) {
  const perSkillCap = typeof opts.perSkillTokenCap === 'number' ? opts.perSkillTokenCap : PER_SKILL_TOKEN_CAP;
  const runBudget = typeof opts.runTokenBudget === 'number' ? opts.runTokenBudget : RUN_TOKEN_BUDGET;

  const ordered = [...(selections || [])].sort(
    (a, b) => (Number(a.skillId) - Number(b.skillId)) || String(a.skillName).localeCompare(String(b.skillName)),
  );

  let runUsed = 0;
  const results = [];

  for (const sel of ordered) {
    const extensions = extensionsForTechnology(sel.technology);
    if (!extensions) {
      results.push({ skillId: sel.skillId, skillName: sel.skillName, technology: sel.technology, files: [], meta: notSampleableMeta(sel.technology) });
      continue;
    }

    const candidates = listCandidateFiles(root, extensions);
    const files = [];
    let usedTokens = 0;
    let totalBytes = 0;
    let truncated = false;
    let capReason = null;

    for (const c of candidates) {
      const estTokens = estTokensFor(c.bytes);
      if (runUsed + estTokens > runBudget) {
        truncated = true;
        if (!capReason) capReason = 'run-budget';
        continue;
      }
      if (usedTokens + estTokens > perSkillCap) {
        truncated = true;
        if (!capReason) capReason = 'per-skill-cap';
        continue;
      }
      const content = readFileSafe(c.abspath);
      if (content === null) continue; // unreadable: skip, don't blow up the run
      files.push({ path: c.path, content, bytes: c.bytes, estTokens });
      usedTokens += estTokens;
      runUsed += estTokens;
      totalBytes += c.bytes;
    }

    results.push({
      skillId: sel.skillId,
      skillName: sel.skillName,
      technology: sel.technology,
      files,
      meta: {
        technology: sel.technology,
        extensions,
        sampleable: true,
        candidateCount: candidates.length,
        includedCount: files.length,
        totalBytes,
        estTokens: usedTokens,
        truncated,
        capReason,
      },
    });
  }

  return results;
}

module.exports = {
  buildSkillSamples,
  listCandidateFiles,
  estTokensFor,
  PER_SKILL_TOKEN_CAP,
  RUN_TOKEN_BUDGET,
  EXCLUDED_DIRS,
  LOCKFILES,
};
